apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ordent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ordent
  template:
    metadata:
      labels:
        app: nginx-ordent
    spec:
      containers:
      - name: nginx
        image: nginx:mainline-alpine3.18-slim
        ports:
        - containerPort: 80
        volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pvc-ordent
